name: CI

on:
  push:
    branches:
      - main
      - release/**
      - '*'
      - '!experimental'
  pull_request:
    branches:
      - main
      - '*'
  pull_request_target:
    types:
      - opened
    branches:
      - '*'
      - main

jobs:
  naive-secret-grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Echo Secrets
        env:
          SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          echo $SECRET





